version: "3.9"

services:
  web-app-1:
    build: .
    ports:
      - 8081:8080
  web-app-2:
    build: .
    ports:
      - 8082:8080

  load-balancer-master:
    build:
      context: load-balancer
      args:
        role: master
    ports:
      - 8080:8080
    cap_add:
      - NET_ADMIN

networks:
  default:
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1